# Default values for spark.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

Spark:
  Path: "/opt/spark"

SharedVolume:
  Name: test-volume
  MountPoint: /mount-minikube
  HostPath: /home/rerngvit/data_folder

Master:
  Name: master
  Image: "rerng007/spark-standalone-k8s"
  ImageTag: "spark-master"
  Replicas: 1
  Component: "spark-master"
  Cpu: "100m"
  Memory: "512Mi"
  ServicePort: 7077
  ContainerPort: 7077
  # Set Master JVM memory. Default 1g
  # DaemonMemory: 1g
  ServiceType: LoadBalancer

WebUi:
  Name: webui
  ServicePort: 8080
  ContainerPort: 8080

Worker:
  Name: worker
  Image: "rerng007/spark-standalone-k8s"
  ImageTag: "spark-worker"
  Replicas: 1
  Component: "spark-worker"
  Cpu: "1000m"
  CpuLimit: "3000m"
  Memory: "1500Mi"
  MemoryLimit: "5000Mi"
  ServicePort: 8081
  ContainerPort: 8081
  # Set Worker JVM memory. Default 1g
  DaemonMemory: "1g"
  # Set how much total memory workers have to give executors
  ExecutorMemory: "3g"
  Autoscaling:
    Enabled: false
  ReplicasMax: 10
  CpuTargetPercentage: 50

Base:
  Name: base
  Image: "rerng007/spark-standalone-k8s"
  ImageTag: "pipeline"
  Replicas: 1
  Component: "spark-base"
  Cpu: "200m"
  CpuLimit: "1000m"
  Memory: "500Mi"
  MemoryLimit: "1000Mi"
  ContainerPort: 8082
  ServicePort: 8082
  ServiceType: ClusterIP
