# Default values for spark.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

Spark:
  Path: "/opt/spark"

SharedVolume:
  Name: test-volume
  MountPoint: /mount-minikube
  HostPath: /data/mount_docker

Master:
  Name: master
  Image: "rerng007/spark-standalone-k8s"
  ImageTag: "spark-master"
  Replicas: 1
  Component: "spark-master"
  Cpu: "100m"
  Memory: "512Mi"
  ServicePort: 7077
  ContainerPort: 7077
  # Set Master JVM memory. Default 1g
  # DaemonMemory: 1g
  ServiceType: ClusterIP

WebUi:
  Name: webui
  ServicePort: 8080
  NodePort: 30000
  ContainerPort: 8080
  ServiceType: NodePort

Worker:
  Name: worker
  Image: "rerng007/spark-standalone-k8s"
  ImageTag: "spark-worker"
  Replicas: 10
  Component: "spark-worker"
  Cpu: "250m"
  CpuLimit: "500m"
  Memory: "5000Mi"
  MemoryLimit: "6000Mi"
  ServicePort: 8081
  ContainerPort: 8081
  # Set Worker JVM memory. Default 1g
  DaemonMemory: "1g"
  # Set how much total memory workers have to give executors
  ExecutorMemory: "4g"
  Autoscaling:
    Enabled: false
  ReplicasMax: 10
  CpuTargetPercentage: 50

Base:
  Name: base
  Image: "rerng007/spark-standalone-k8s"
  ImageTag: "pipeline"
  Replicas: 1
  Component: "spark-base"
  Cpu: "500m"
  CpuLimit: "1000m"
  Memory: "3000Mi"
  MemoryLimit: "5000Mi"
  Jupyter_NodePort: 30088
  Jupyter_ContainerPort: 8888
  SparkAppUI_NodePort: 30040
  SparkAppUI_ContainerPort: 4040
  Airflow_NodePort: 30080
  Airflow_ContainerPort: 8080 
  ContainerPort: 4040
  ServicePort: 8082  
  ServiceType: ClusterIP
