apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "base-fullname" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Release.Name }}-{{ .Values.Base.Component }}"
spec:
  replicas: {{ default 1 .Values.Base.Replicas }}
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      component: "{{ .Release.Name }}-{{ .Values.Base.Component }}"
  template:
    metadata:
      labels:
        heritage: {{ .Release.Service | quote }}
        release: {{ .Release.Name | quote }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        component: "{{ .Release.Name }}-{{ .Values.Base.Component }}"
    spec:
      containers:
        - name: {{ template "base-fullname" . }}
          image: "{{ .Values.Base.Image }}:{{ .Values.Base.ImageTag }}"
          imagePullPolicy: Always
          command: ["/wait-for-step.sh", "/bin/bash"]
          ports:
            - containerPort: {{ .Values.Base.ContainerPort }}
          resources:
            requests:
              cpu: "{{ .Values.Base.Cpu }}"
              memory: "{{ .Values.Base.Memory }}"
          env:
          - name: SPARK_MASTER_HOST
            value: {{ template "master-fullname" . }}
          - name: SPARK_MASTER_PORT
            value: {{ .Values.Master.ServicePort | quote }}
          - name: SPARK_MASTER_WEBUI_PORT
            value: {{ .Values.WebUi.ContainerPort | quote }}
