apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "tfhub-flask-fullname" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Release.Name }}-{{ .Values.TFHubFlask.Component }}"
spec:
  replicas: {{ default 1 .Values.TFHubFlask.Replicas }}
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      component: "{{ .Release.Name }}-{{ .Values.TFHubFlask.Component }}"
  template:
    metadata:
      labels:
        heritage: {{ .Release.Service | quote }}
        release: {{ .Release.Name | quote }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        component: "{{ .Release.Name }}-{{ .Values.TFHubFlask.Component }}"
    spec:
      containers:
        - name: {{ template "tfhub-flask-fullname" . }}
          image: "{{ .Values.TFHubFlask.Image }}:{{ .Values.TFHubFlask.ImageTag }}"
          imagePullPolicy: Always
          command: ["python3", "src/app.py"]
          ports:
            - containerPort: {{ .Values.TFHubFlask.ContainerPort }}
          resources:
            requests:
              cpu: "{{ .Values.TFHubFlask.Cpu }}"
              memory: "{{ .Values.TFHubFlask.Memory }}"
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "tfhub-flask-fullname" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Release.Name }}-{{ .Values.TFHubFlask.Component }}"
spec:
  ports:
    - port: {{ .Values.TFHubFlask.ServicePort }}
      targetPort: {{ .Values.TFHubFlask.ContainerPort }}
  selector:
    component: "{{ .Release.Name }}-{{ .Values.TFHubFlask.Component }}"
  type: {{ .Values.TFHubFlask.ServiceType }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.TFHubFlaskNodePort.Name }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Release.Name }}-{{ .Values.TFHubFlask.Component }}"
spec:
  ports:
    - port: {{ .Values.TFHubFlaskNodePort.ServicePort }}
      targetPort: {{ .Values.TFHubFlaskNodePort.ContainerPort }}
      nodePort: {{ .Values.TFHubFlaskNodePort.NodePort }}
  selector:
    component: "{{ .Release.Name }}-{{ .Values.TFHubFlask.Component }}"
  type: NodePort

