# Default values for spark.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

TFHubFlask:
  Name: tfhub-flask
  Image: "rerng007/ml-models"
  ImageTag: "tfhub"
  Replicas: 3
  Component: "tfhub-flask-cluster"
  Cpu: "500m"
  Memory: "4000Mi"
  ContainerPort: 9090 
  ServicePort: 9091
  NodePort: 30090
  ServiceType: NodePort
