# Default values for spark.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

TFHubFlask:
  Name: tfhub-flask
  Image: "rerng007/ml-models"
  ImageTag: "tfhub"
  Replicas: 2
  Component: "tfhub-flask-cluster"
  Cpu: "250m"
  Memory: "3000Mi"
  CpuLimit: "500m"
  MemoryLimit: "8000Mi"
  ContainerPort: 9090 
  ServicePort: 9091
  ServiceType: ClusterIP
  Autoscaling:
    Enabled: True
  ReplicasMax: 10
  CpuTargetPercentage: 50


TFHubFlaskNodePort:
  Name: tfhub-flask-np-service
  ContainerPort: 9090 
  ServicePort: 9092  
  NodePort: 30090
  Component: "tfhub-flask-cluster"

