# Default values for spark.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

SharedVolume:
  Name: test-volume
  MountPoint: /mount-minikube
  HostPath: /data/mount_docker

Spark:
  Path: "/opt/spark"

Base:
  Name: base
  Image: "rerng007/spark-native-k8s"
  ImageTag: "pipeline"
  Replicas: 1
  Component: "spark-base"
  Cpu: "500m"
  Memory: "512Mi"
  ContainerPort: 8082
  ServicePort: 8082
  ServiceType: ClusterIP
