# Default values for spark.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

Spark:
  Path: "/opt/spark"

Base:
  Name: base
  Image: "rerng007/spark-standalone-k8s"
  ImageTag: "pipeline"
  Replicas: 1
  Component: "spark-base"
  Cpu: "100m"
  Memory: "512Mi"
  ContainerPort: 8082
  ServicePort: 8082
  ServiceType: ClusterIP
