apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "base-fullname" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Release.Name }}-{{ .Values.Base.Component }}"
spec:
  replicas: {{ default 1 .Values.Base.Replicas }}
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      component: "{{ .Release.Name }}-{{ .Values.Base.Component }}"
  template:
    metadata:
      labels:
        heritage: {{ .Release.Service | quote }}
        release: {{ .Release.Name | quote }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        component: "{{ .Release.Name }}-{{ .Values.Base.Component }}"
    spec:
      serviceAccountName: spark
      volumes:
      - name: test
        hostPath:
          # directory location on host
          path: /home/docker
          type: Directory
      containers:
        - name: {{ template "base-fullname" . }}
          image: "{{ .Values.Base.Image }}:{{ .Values.Base.ImageTag }}"
          volumeMounts:
          - name: test
            mountPath: /mount-minikube
          imagePullPolicy: Always
          command: ["/wait-for-step.sh", "/bin/bash"]
          ports:
            - containerPort: {{ .Values.Base.ContainerPort }}
          resources:
            requests:
              cpu: "{{ .Values.Base.Cpu }}"
              memory: "{{ .Values.Base.Memory }}"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark
  namespace: default
  selfLink: /api/v1/namespaces/default/serviceaccounts/spark
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: 2019-03-17T15:52:47Z
  name: spark-role
  resourceVersion: "1072734"
  selfLink: /apis/rbac.authorization.k8s.io/v1/clusterrolebindings/spark-role
  uid: b62c84ab-48cc-11e9-b623-00155d380112
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: ServiceAccount
  name: spark
  namespace: default
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "base-fullname" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Release.Name }}-{{ .Values.Base.Component }}"
spec:
  ports:
    - port: {{ .Values.Base.ServicePort }}
      targetPort: {{ .Values.Base.ContainerPort }}
  selector:
    component: "{{ .Release.Name }}-{{ .Values.Base.Component }}"
  type: {{ .Values.Base.ServiceType }}
  clusterIP: None