# Default values for spark.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

Spark:
  Path: "/opt/spark"

Master:
  Name: master
  Image: "rerng007/spark-standalone-k8s"
  ImageTag: "spark-master"
  Replicas: 1
  Component: "spark-master"
  Cpu: "100m"
  Memory: "512Mi"
  ServicePort: 7077
  ContainerPort: 7077
  # Set Master JVM memory. Default 1g
  # DaemonMemory: 1g
  ServiceType: LoadBalancer

WebUi:
  Name: webui
  ServicePort: 8080
  ContainerPort: 8080

Worker:
  Name: worker
  Image: "rerng007/spark-standalone-k8s"
  ImageTag: "spark-worker"
  Replicas: 3
  Component: "spark-worker"
  Cpu: "100m"
  Memory: "512Mi"
  ServicePort: 8081
  ContainerPort: 8081
  # Set Worker JVM memory. Default 1g
  # DaemonMemory: 1g
  # Set how much total memory workers have to give executors
  # ExecutorMemory: 1g
  Autoscaling:
    Enabled: false
  ReplicasMax: 10
  CpuTargetPercentage: 50

Base:
  Name: base
  Image: "bde2020/spark-base"
  ImageTag: "2.4.0-hadoop2.7"
  Replicas: 1
  Component: "spark-base"
  Cpu: "100m"
  Memory: "512Mi"
  ContainerPort: 8082
  ServicePort: 8082
  ServiceType: NodePort
